// Real jobs from local tenant_carltonelectric. GIT-IGNORED, local preview only.
// Full sets (not a sample slice):
//  - REAL_NEEDS_JOBS      = all 57 In-Progress jobs that have a forecast staffing need.
//    'needed' = the job's peak weekly need; hours = actual vs projected-at-completion.
//  - REAL_PROJECTED_JOBS  = all 54 In-Progress jobs with a projected-hours total.
export const REAL_NEEDS_JOBS = [
  { name: "Holly Hills Repl ES", id: "#25011", status: "In-Progress", needed: "36 needed", actualHours: "13,332h", projectedHours: "30,197h", actualPercent: 44, calendarPercent: 73 },
  { name: "DPS Aspen Hall Renovation", id: "#RVT-836115", status: "In-Progress", needed: "32 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 0 },
  { name: "CCSD-CCHS - Academics Ph1", id: "#26007", status: "In-Progress", needed: "28 needed", actualHours: "449h", projectedHours: "4,219h", actualPercent: 11, calendarPercent: 11 },
  { name: "Commerce Yards", id: "#26003", status: "In-Progress", needed: "20 needed", actualHours: "616h", projectedHours: "7,183h", actualPercent: 9, calendarPercent: 20 },
  { name: "BVSD Fairview HS", id: "#25026", status: "In-Progress", needed: "19 needed", actualHours: "7,598h", projectedHours: "10,460h", actualPercent: 73, calendarPercent: 82 },
  { name: "DCSD Legacy Ph II", id: "#25033", status: "In-Progress", needed: "14 needed", actualHours: "12,048h", projectedHours: "12,017h", actualPercent: 100, calendarPercent: 85 },
  { name: "Falcon Comm Ctr Bldg B", id: "#24074", status: "In-Progress", needed: "14 needed", actualHours: "2,293h", projectedHours: "2,293h", actualPercent: 100, calendarPercent: 100 },
  { name: "Izzio Bakery - Thornton", id: "#25002", status: "In-Progress", needed: "12 needed", actualHours: "25,659h", projectedHours: "25,660h", actualPercent: 100, calendarPercent: 100 },
  { name: "BVSD Critical Needs CTE", id: "#24087", status: "In-Progress", needed: "11 needed", actualHours: "9,659h", projectedHours: "10,610h", actualPercent: 91, calendarPercent: 92 },
  { name: "BVSD Southern Hills MS", id: "#25027", status: "In-Progress", needed: "11 needed", actualHours: "4,332h", projectedHours: "5,260h", actualPercent: 82, calendarPercent: 82 },
  { name: "DPS Bradley Mech Upgrades", id: "#25038", status: "In-Progress", needed: "11 needed", actualHours: "1,639h", projectedHours: "2,066h", actualPercent: 79, calendarPercent: 44 },
  { name: "Falcon Bldg B Mods-ACCO", id: "#26004", status: "In-Progress", needed: "11 needed", actualHours: "2,840h", projectedHours: "2,841h", actualPercent: 100, calendarPercent: 36 },
  { name: "Mountain Vista HS", id: "#25060", status: "In-Progress", needed: "11 needed", actualHours: "2,020h", projectedHours: "1,839h", actualPercent: 100, calendarPercent: 32 },
  { name: "AERO 70", id: "#24084", status: "In-Progress", needed: "10 needed", actualHours: "8,910h", projectedHours: "9,569h", actualPercent: 93, calendarPercent: 0 },
  { name: "Arrupe Jesuit HS", id: "#24031", status: "In-Progress", needed: "10 needed", actualHours: "23,538h", projectedHours: "23,725h", actualPercent: 99, calendarPercent: 92 },
  { name: "Mountain View Fire ST #15", id: "#24063", status: "In-Progress", needed: "10 needed", actualHours: "7,696h", projectedHours: "7,585h", actualPercent: 100, calendarPercent: 100 },
  { name: "Windsor Fire Alarm Repl", id: "#24090", status: "In-Progress", needed: "10 needed", actualHours: "7,775h", projectedHours: "7,808h", actualPercent: 100, calendarPercent: 100 },
  { name: "Aspen Birch Chiller", id: "#25021", status: "In-Progress", needed: "9 needed", actualHours: "3,650h", projectedHours: "3,650h", actualPercent: 100, calendarPercent: 67 },
  { name: "Fueling", id: "#RVT-68906", status: "In-Progress", needed: "9 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 65 },
  { name: "Izzio ASI 5", id: "#25059", status: "In-Progress", needed: "9 needed", actualHours: "4,156h", projectedHours: "4,183h", actualPercent: 99, calendarPercent: 68 },
  { name: "Roxborough Primary School", id: "#25063", status: "In-Progress", needed: "9 needed", actualHours: "1,960h", projectedHours: "2,376h", actualPercent: 82, calendarPercent: 31 },
  { name: "Erie Police Dept Add Reno", id: "#25046", status: "In-Progress", needed: "8 needed", actualHours: "2,236h", projectedHours: "17,217h", actualPercent: 13, calendarPercent: 25 },
  { name: "Mountain View Fire W.Mead", id: "#25040", status: "In-Progress", needed: "8 needed", actualHours: "3,727h", projectedHours: "8,039h", actualPercent: 46, calendarPercent: 35 },
  { name: "WIC HQ Expansion", id: "#25051", status: "In-Progress", needed: "8 needed", actualHours: "3,740h", projectedHours: "6,286h", actualPercent: 59, calendarPercent: 26 },
  { name: "WPS Shaw Heights MS", id: "#24006", status: "In-Progress", needed: "8 needed", actualHours: "11,431h", projectedHours: "11,402h", actualPercent: 100, calendarPercent: 100 },
  { name: "Pre-Fab", id: "#RVT-38298", status: "In-Progress", needed: "7 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 69 },
  { name: "Roxborough Intermediate", id: "#25062", status: "In-Progress", needed: "7 needed", actualHours: "1,618h", projectedHours: "2,012h", actualPercent: 80, calendarPercent: 31 },
  { name: "Support for Fuel/Service", id: "#RVT-803698", status: "In-Progress", needed: "7 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 15 },
  { name: "27J Talon Ridge MS", id: "#24036", status: "In-Progress", needed: "6 needed", actualHours: "38,226h", projectedHours: "38,228h", actualPercent: 100, calendarPercent: 100 },
  { name: "APS Freezer-Warehouse Bld", id: "#25056", status: "In-Progress", needed: "6 needed", actualHours: "522h", projectedHours: "6,230h", actualPercent: 8, calendarPercent: 36 },
  { name: "Highlands Ranch HS Auto", id: "#25036", status: "In-Progress", needed: "6 needed", actualHours: "3,812h", projectedHours: "4,536h", actualPercent: 84, calendarPercent: 97 },
  { name: "Academy of Charters Reno", id: "#25003", status: "In-Progress", needed: "5 needed", actualHours: "6,570h", projectedHours: "6,672h", actualPercent: 98, calendarPercent: 100 },
  { name: "DPS Valdez Elem Sch Proj", id: "#25050", status: "In-Progress", needed: "5 needed", actualHours: "842h", projectedHours: "1,809h", actualPercent: 47, calendarPercent: 40 },
  { name: "Special Projects", id: "#RVT-55988", status: "In-Progress", needed: "5 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 67 },
  { name: "Vacations/LOAs", id: "#TMP-26001", status: "In-Progress", needed: "5 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 27 },
  { name: "Altus Westminster", id: "#24088", status: "In-Progress", needed: "4 needed", actualHours: "2,926h", projectedHours: "2,926h", actualPercent: 100, calendarPercent: 77 },
  { name: "DCHS Cosmetology CTE", id: "#25035", status: "In-Progress", needed: "4 needed", actualHours: "2,380h", projectedHours: "2,501h", actualPercent: 95, calendarPercent: 100 },
  { name: "Picadilly Crossing", id: "#24077", status: "In-Progress", needed: "4 needed", actualHours: "666h", projectedHours: "6,260h", actualPercent: 11, calendarPercent: 67 },
  { name: "Signature Aviate APA Hang", id: "#25023", status: "In-Progress", needed: "4 needed", actualHours: "40h", projectedHours: "3,384h", actualPercent: 1, calendarPercent: 27 },
  { name: "WPS SHAW/FLYNN-Summer Wrk", id: "#26008", status: "In-Progress", needed: "4 needed", actualHours: "768h", projectedHours: "999h", actualPercent: 77, calendarPercent: 0 },
  { name: "Clear Creek Crossing", id: "#25045", status: "In-Progress", needed: "3 needed", actualHours: "1,037h", projectedHours: "1,074h", actualPercent: 97, calendarPercent: 44 },
  { name: "Clinica Family Heath Reno", id: "#24029", status: "In-Progress", needed: "3 needed", actualHours: "2,596h", projectedHours: "2,596h", actualPercent: 100, calendarPercent: 0 },
  { name: "Fire Alarm/Floating", id: "#RVT-719554", status: "In-Progress", needed: "3 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 31 },
  { name: "Poudre Valley CO-OP", id: "#25012", status: "In-Progress", needed: "3 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 74 },
  { name: "Titan Compark N. Bldg 1-2", id: "#26011", status: "In-Progress", needed: "3 needed", actualHours: "238h", projectedHours: "2,856h", actualPercent: 8, calendarPercent: 0 },
  { name: "CEMCO", id: "#25054", status: "In-Progress", needed: "2 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 100 },
  { name: "Griswold WPF HVAC Repl", id: "#24032", status: "In-Progress", needed: "2 needed", actualHours: "1,856h", projectedHours: "1,852h", actualPercent: 100, calendarPercent: 100 },
  { name: "King Soopers Fuel #142", id: "#25041", status: "In-Progress", needed: "2 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 48 },
  { name: "MSR Logistics Facility", id: "#26013", status: "In-Progress", needed: "2 needed", actualHours: "11h", projectedHours: "1,388h", actualPercent: 1, calendarPercent: 0 },
  { name: "Mountain Ridge MS", id: "#25061", status: "In-Progress", needed: "2 needed", actualHours: "417h", projectedHours: "554h", actualPercent: 75, calendarPercent: 0 },
  { name: "Murphy USA #23110", id: "#25048", status: "In-Progress", needed: "2 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 50 },
  { name: "PH 2 Lookout Improvements", id: "#25047", status: "In-Progress", needed: "2 needed", actualHours: "945h", projectedHours: "1,249h", actualPercent: 76, calendarPercent: 51 },
  { name: "Project Waterfall", id: "#25049", status: "In-Progress", needed: "2 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 47 },
  { name: "RMMA UL Tank", id: "#25032", status: "In-Progress", needed: "2 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 100 },
  { name: "Hidden Lake Apt Elevator", id: "#25024", status: "In-Progress", needed: "1 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 100 },
  { name: "Suncor #152", id: "#25058", status: "In-Progress", needed: "1 needed", actualHours: "0h", projectedHours: "0h", actualPercent: 0, calendarPercent: 100 },
  { name: "WIC Blast Tunnel Exten.", id: "#25057", status: "In-Progress", needed: "1 needed", actualHours: "2h", projectedHours: "2h", actualPercent: 100, calendarPercent: 39 },
]

export const REAL_PROJECTED_JOBS = [
  { name: "27J Talon Ridge MS", operationHours: 38226, planningHours: 38228 },
  { name: "Holly Hills Repl ES", operationHours: 13333, planningHours: 30197 },
  { name: "Izzio Bakery - Thornton", operationHours: 25659, planningHours: 25660 },
  { name: "Arrupe Jesuit HS", operationHours: 23538, planningHours: 23725 },
  { name: "Erie Police Dept Add Reno", operationHours: 2237, planningHours: 17217 },
  { name: "DCSD Legacy Ph II", operationHours: 12048, planningHours: 12017 },
  { name: "WPS Shaw Heights MS", operationHours: 11431, planningHours: 11402 },
  { name: "BVSD Critical Needs CTE", operationHours: 9659, planningHours: 10610 },
  { name: "BVSD Fairview HS", operationHours: 7599, planningHours: 10460 },
  { name: "AERO 70", operationHours: 8910, planningHours: 9569 },
  { name: "Brighton Fire Training", operationHours: 8169, planningHours: 8170 },
  { name: "Mountain View Fire W.Mead", operationHours: 3727, planningHours: 8039 },
  { name: "Windsor Fire Alarm Repl", operationHours: 7775, planningHours: 7808 },
  { name: "Mountain View Fire ST #15", operationHours: 7696, planningHours: 7585 },
  { name: "Commerce Yards", operationHours: 616, planningHours: 7183 },
  { name: "Academy of Charters Reno", operationHours: 6571, planningHours: 6672 },
  { name: "WIC HQ Expansion", operationHours: 3740, planningHours: 6286 },
  { name: "Falcon Comm Ctr Bldg A", operationHours: 6280, planningHours: 6271 },
  { name: "Picadilly Crossing", operationHours: 666, planningHours: 6260 },
  { name: "APS Freezer-Warehouse Bld", operationHours: 522, planningHours: 6230 },
  { name: "BVSD Southern Hills MS", operationHours: 4332, planningHours: 5260 },
  { name: "Highlands Ranch HS Auto", operationHours: 3812, planningHours: 4536 },
  { name: "Denver Zoo Sea Lions", operationHours: 4476, planningHours: 4476 },
  { name: "CCSD-CCHS - Academics Ph1", operationHours: 449, planningHours: 4219 },
  { name: "Izzio ASI 5", operationHours: 4156, planningHours: 4183 },
  { name: "Aspen Birch Chiller", operationHours: 3651, planningHours: 3651 },
  { name: "Weld 7 New Central Office", operationHours: 5321, planningHours: 3493 },
  { name: "Signature Aviate APA Hang", operationHours: 40, planningHours: 3384 },
  { name: "Altus Westminster", operationHours: 2926, planningHours: 2926 },
  { name: "Titan Compark N. Bldg 1-2", operationHours: 239, planningHours: 2856 },
  { name: "Falcon Bldg B Mods-ACCO", operationHours: 2841, planningHours: 2841 },
  { name: "Clinica Family Heath Reno", operationHours: 2596, planningHours: 2596 },
  { name: "DCHS Cosmetology CTE", operationHours: 2381, planningHours: 2501 },
  { name: "Roxborough Primary School", operationHours: 1960, planningHours: 2376 },
  { name: "Falcon Comm Ctr Bldg B", operationHours: 2293, planningHours: 2293 },
  { name: "DPS Bradley Mech Upgrades", operationHours: 1639, planningHours: 2066 },
  { name: "Roxborough Intermediate", operationHours: 1618, planningHours: 2013 },
  { name: "Griswold WPF HVAC Repl", operationHours: 1857, planningHours: 1853 },
  { name: "Mountain Vista HS", operationHours: 2020, planningHours: 1839 },
  { name: "DPS Valdez Elem Sch Proj", operationHours: 842, planningHours: 1809 },
  { name: "DPS Schmitt Elevator Reno", operationHours: 1469, planningHours: 1469 },
  { name: "MSR Logistics Facility", operationHours: 11, planningHours: 1388 },
  { name: "PH 2 Lookout Improvements", operationHours: 945, planningHours: 1249 },
  { name: "Clear Creek Crossing", operationHours: 1037, planningHours: 1074 },
  { name: "WPS SHAW/FLYNN-Summer Wrk", operationHours: 768, planningHours: 999 },
  { name: "Murphy USA #7982", operationHours: 15, planningHours: 811 },
  { name: "DCSD Legacy CIP", operationHours: 230, planningHours: 559 },
  { name: "Mountain Ridge MS", operationHours: 417, planningHours: 554 },
  { name: "King Soopers Fuel #152", operationHours: 95, planningHours: 435 },
  { name: "DPS Central Kitchen", operationHours: 445, planningHours: 300 },
  { name: "Alta #6149", operationHours: 34, planningHours: 283 },
  { name: "DCHS Security Vestibules", operationHours: 467, planningHours: 254 },
  { name: "CEMCO Production Lighting", operationHours: 6, planningHours: 6 },
  { name: "WIC Blast Tunnel Exten.", operationHours: 2, planningHours: 2 },
]
